### ISSUE TITLE
Two typos in CADL/session-2/lecture-2.ipynb

### ISSUE THREAD

**Issue by psoulos** [pkmital/CADL#31]
When constructing the first bias, the comment says to use a constant value of 0 but the code initializes the value to 1

\# For bias variables, we usually start with a constant value of 0.
B = tf.Variable(tf.constant([1], dtype=tf.float32), name='bias')

In the section where you reconstruct the astronaut image, the markdown says that you're going to redraw the image every 10 iterations, but the code actually uses 20 iterations: 

"Every 10 iterations, we're going to draw the predicted image by evaluating the predicted image tensor, Y_pred, and giving it every location in the image to predict, the xs array."

if (it_i + 1) % 20 == 0:

**Comment by pkmital** [comment]
TY https://github.com/pkmital/CADL/pull/33 fixed it!
