### ISSUE TITLE
Just to respect 2.7

### ISSUE THREAD

**Issue by dattasaurabh82** [pkmital/CADL#4]
I know you started the course with py3.0
Some people like using 2.7 (like me). Not complaining, just if I may, I'd like to include the changes I'd make in code accordingly for 2.7. 

Like the one in session - 0 notebook, urllib's request module doesn't exist for 2.7, so 
basically two places you have change
`from urllib import request`
 becomes
`import urllib`
And
`urllib.request.urlretrieve(....`
becomes
 `urllib.urlretrieve(....`
Also 
`print (url, end=..)`
will not work. So may be we can just write
`print (url)`

**Comment by pkmital** [comment]
I personally thought a lot of the code added by utils like `pasteurize` from `future_utils`: http://python-future.org/overview.html - would just make things more opaque for people less familiar with Python programming, and that a better solution would be to use another python environment with Python 3.  With Anaconda, pyenv, or Docker, these are all very easy to do.  Some of the changes are definitely as easy as you've listed, and do not require `future_utils`, but as we get into later session, I think they become more opaque and less friendly.  I could be wrong though.

**Comment by dattasaurabh82** [comment]
Hey .. Thanks .. I actually wrote the issue without thinking much .. (Now when I thought about it), I was like okay may be I could've been less of a **** and done an `anaconda ` env myself ..My bad ..  But yeah thanks for reminding about the `pasteurize` .. Will keep that in mind ..

**Comment by pkmital** [comment]
No worries at all!  It's definitely a concern I had as well.

**Comment by pkmital** [comment]
Going to close this for now!

**Comment by dattasaurabh82** [comment]
cool thanks

*Saurabh Datta*
IDP 201*4 Alumni*
*Copenhagen Institute of Interaction Design*

//////////////////////////////////////////////////////////////////////////
*mobile(CN)*:------------ -+86 15201802814
*Primary email:----------*dattasaurabh82@gmail.com
*School email:-----------*s.datta@edu.ciid.dk
*Work email:--------------*saurabh.datta@frogdesign.com
*Portfolio:-----------------.dattasaurabh.com
<http://www.dattasaurabh.com/>*
*//////////////////////////////////////////////////////////////////////////*


*Tumbler <http://dattasaurabh82.tumblr.com/> github
<https://github.com/dattasaurabh82> twitter
<https://twitter.com/dattasaurabh82> facebook
<https://www.facebook.com/dattasaurabh82> wordpress
<https://dattasaurabh82.wordpress.com/>*
