### ISSUE TITLE
MacOS without docker

### ISSUE THREAD

**Issue by martin-martin** [pkmital/CADL#44]
Hei!
I'm working on a Mac and (think) I don't really need to use docker, since I have all the libraries (including tensorflow) installed and also jupyter notebooks running.

I was thinking that you could add instructions about working with such a setup - or is there a specific reason to discourage this?

Thanks : )

**Comment by pkmital** [comment]
Sure just skip ahead to https://github.com/pkmital/CADL#jupyter-notebook where it suggests to download the Anaconda Python 3.5+ distribution and make sure you have installed the necessary pip package for TensorFlow: https://github.com/pkmital/CADL#installing-python-packages

The instructions could definitely use some reworking to show that OSX/Linux users do not have to use Docker.  If you would like to submit a PR i'd be happy to review!

**Comment by pkmital** [comment]
I've edited the instructions to include a "Quickstart Guide" which does not require Docker... hopefully this makes it clearer to users more proficient w/ installing libraries.
