### ISSUE TITLE
Conversion missing in session-3.ipynb

### ISSUE THREAD

**Issue by borisd13** [pkmital/CADL#50]
In the file "session-3.ipynb", the line
> recon = utils.montage(clipped)

should be replaced with
> recon = utils.montage(clipped).astype(np.uint8)

Otherwise the generated pictures will not display correctly.

**Comment by pkmital** [comment]
This is somewhat up to the user and the way they normalize/preprocess/send data so I would probably suggest to instead include a note about casting the image rather than forcing the cast to uint8.
