### ISSUE TITLE
Denoising VAE implementation broken

### ISSUE THREAD

**Issue by sunsided** [pkmital/CADL#56]
In the code for the `VAE` function ([lines 97-102](https://github.com/pkmital/CADL/blob/bcdb0191ce65c29e8434243aab2016dd89a1b752/session-3/libs/vae.py#L97-L102) as per bcdb0191ce65c29e8434243aab2016dd89a1b752) appears to be a bug that prevents the usage of corrupted inputs:

```python
    if denoising:
        current_input = utils.corrupt(x) * corrupt_prob + x * (1 - corrupt_prob)

    # 2d -> 4d if convolution
    x_tensor = utils.to_tensor(x) if convolutional else x
    current_input = x_tensor
```

Here, the `current_input` tensor is directly overwritten by `x_tensor`. It appears to be the case for all sessions.

**Comment by pkmital** [comment]
Nice catch!  Feel free to submit a PR.

**Comment by sunsided** [comment]
Uncool dude, I'm paying money for the course. :expressionless: [Here's](https://github.com/pkmital/CADL/pull/58) a fix - not sure though if this is what you had in mind, style and all. Hope it doesn't break more than it fixes. :sweat_smile:
