### ISSUE TITLE
Docker-gpu dockerfile build issue

### ISSUE THREAD

**Issue by ljstrnadiii** [pkmital/CADL#70]
Hey @pkmital, 

Awesome work!! I am really excited to dig into what you have going on. I really appreciate how well you document tf and offer docker builds with and without gpu.

I am having a problem building the gpu docker file. Of course it has to do with cuDNN. I am not sure why they make it so difficult to get a hold of that. Anyways, here is my last few lines of my docker build output:

```
sha256sum: WARNING: 1 computed checksum did NOT match
The command '/bin/sh -c CUDNN_DOWNLOAD_SUM=a87cb2df2e5e7cc0a05e266734e679ee1a2fadad6f06af82a76ed81a23b102c8 &&     curl -fsSL http://developer.download.nvidia.com/compute/redist/cudnn/v5.1/cudnn-8.0-linux-x64-v5.1.tgz -O &&     echo "$CUDNN_DOWNLOAD_SUM  cudnn-8.0-linux-x64-v5.1.tgz" | sha256sum -c --strict - &&     tar -xzf cudnn-8.0-linux-x64-v5.1.tgz -C /usr/local --wildcards 'cuda/lib64/libcudnn.so.*' &&     rm cudnn-8.0-linux-x64-v5.1.tgz &&     ldconfig &&     ln -s /usr/local/cuda/lib64/libcudnn.so.5 /usr/local/cuda/lib64/libcudnn.so' returned a non-zero code: 1
```

Maybe you want to use the caffe:0.15 base image (#71) to avoid the problem? I think they are different between ubuntu 14 and 16.

**Comment by RinatMenyashev** [comment]
+1 faced the same problem on amazon ubuntu p2 instance

**Comment by pkmital** [comment]
Fixed w/ https://github.com/pkmital/CADL/commit/b55c0abe1053da0a341db8129b39889c4bd9b40d
