### ISSUE TITLE
Small potential error

### ISSUE THREAD

**Issue by RiaanZoetmulder** [pkmital/CADL#84]
Hello,

I see in your ipython notebook about VAEGANs, this in your variational step:

z_mu = tf.nn.tanh(utils.linear(h, n_code, name='mu')[0])
z_log_sigma = 0.5 * tf.nn.tanh(utils.linear(h, n_code, name='log_sigma')[0])

Why are you applying the tanh activation here?

**Comment by pkmital** [comment]
Good catch!  That should be a normal linear layer without tanh activation.
