### ISSUE TITLE
lecture 4 : isn't there an issue with h,w ; in cell 31 ? 

### ISSUE THREAD

**Issue by vichug** [pkmital/CADL#92]
Cell 31 of the lecture notebook shows :
```
def total_variation_loss(x):
    h, w = x.get_shape().as_list()[1], x.get_shape().as_list()[1]
```

Shouldn't it be :
```
def total_variation_loss(x):
    h, w = x.get_shape().as_list()[1], x.get_shape().as_list()[2]
```
?

**Comment by pkmital** [comment]
Good catch!  I guess we better include some non-square images in our tests ;)  Feel free to open a PR if you want or else I will be sure to include this in the next update.

**Comment by vichug** [comment]
PR opened :)
